### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jarrodscott** [jmw86069/jamba#1]
Hi!

I have tried updating `devtools` and `remotes` but I still get an error when I try to install `jamba`.  Any ideas would be very appreciated :)

`remotes::install_github("jmw86069/jamba")`

```
Downloading GitHub repo jmw86069/jamba@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/jmw86069/jamba/tarball/HEAD' failed
```

**Comment by jmw86069** [comment]
Hey thanks for posting the issue!
I tried to reproduce the problem, and I don't see an error. However, I'll help troubleshoot best I can.

The error seems to come from `remotes` calling `utils::download.file()`. I did a quick search of similar errors, and found two potential workarounds.

1. If you're running MS Windows, a possible workaround is described here: https://github.com/r-lib/remotes/issues/130#issuecomment-423830669
In short, open Windows "Internet Options" and check the box "Use TLS 1.2"
Seems to be related to using "https" instead of "http". This workaround is probably not relevant if you have recently installed Github R packages without error.

2. Another workaround is to set this option to use libcurl, then try to install:
```
options(download.file.method = "libcurl")
remotes::install_github("jmw86069/jamba")
```

If those options fail, or are not relevant, can you send info about the OS, R version and package version of "remotes" and "utils"? The R commands below should do it.

```
osVersion
R.version.string
packageVersion("remotes")
packageVersion("utils")
```

Thank you!

**Comment by jarrodscott** [comment]
Hi @jmw86069 

Sorry, I'm not normally so lazy that I fail to include this type of info :)

I tried option #2 and I got the same error message. 

```
osVersion: macOS Catalina 10.15.7 
R.version.string
[1] "R version 4.0.4 (2021-02-15)"
> packageVersion("remotes")
[1] ‘2.3.0’
> packageVersion("utils")
[1] ‘4.0.4’
```

**Comment by jmw86069** [comment]
This is so odd! No idea why the download step itself would fail.

These steps may not be helpful for whatever is happening, but can you try just the download step?
```
utils::download.file(
   url='https://api.github.com/repos/jmw86069/jamba/tarball/HEAD',
   destfile="jamba-0.0.62.900.tgz")
```

For me it downloads a 58Mb file. If this is the problem step, this may fail for you as well.

**Comment by jmw86069** [comment]
I saw some comments that suggested `devtools::` might work when `remotes::` fails... might be worth a try.

```
devtools::install_github("jmw86069/jamba")
```

The issues I have seen in past had more informative error messages. :) Unable to download the file itself suggests either it cannot connect - or cannot save the file. For long-running R sessions, I found sometimes the `tempdir()` gets deleted server-side, and creating the tempdir again fixed that problem, e.g. `dir.create(tempdir())` ... random guesses though!

Related discussion: https://community.rstudio.com/t/remotes-install-github-working-in-r-session-but-not-in-rstudio-server/27464/6

**Comment by jarrodscott** [comment]
I think you may be on to something. When I run 

```
utils::download.file(
    url='https://api.github.com/repos/jmw86069/jamba/tarball/HEAD',
    destfile="jamba-0.0.62.900.tgz")
```

I get the following error:

```
trying URL 'https://api.github.com/repos/jmw86069/jamba/tarball/HEAD'
downloaded 39.9 MB

Error in utils::download.file(url = "https://api.github.com/repos/jmw86069/jamba/tarball/HEAD",  : 
  download from 'https://api.github.com/repos/jmw86069/jamba/tarball/HEAD' failed
In addition: Warning message:
In utils::download.file(url = "https://api.github.com/repos/jmw86069/jamba/tarball/HEAD",  :
  URL 'https://codeload.github.com/jmw86069/jamba/legacy.tar.gz/HEAD': Timeout of 60 seconds was reached
```

The actual size of the download is 41.8Mb. I looked at the `tempdir()` and it is still there. When I run  `dir.create(tempdir())` I get a message saying it already exists. I also tried running `devtools::install_github("jmw86069/jamba")` but that failed too. Finally, I was able to install successfully on our server (details below) by running `remotes::install_github("jmw86069/jamba")` so it seems it is either a problem with my local connection or something related to my mac R install? I will continue to troubleshoot and let you know what I come up with :) Thanks @jmw86069 for your help! 

```
os.version: CentOS 7.6
> R.version.string
[1] "R version 4.0.0 (2020-04-24)"
> packageVersion("remotes")
[1] ‘2.2.0’
> packageVersion("utils")
[1] ‘4.0.0’
```

**Comment by jarrodscott** [comment]
OK! I changed the `timeout` time.

```
getOption('timeout')
[1] 60
options(timeout=100)
```

and reran

```
utils::download.file(
+    url='https://api.github.com/repos/jmw86069/jamba/tarball/HEAD',
+    destfile="jamba-0.0.62.900.tgz")
```

Success!

```
trying URL 'https://api.github.com/repos/jmw86069/jamba/tarball/HEAD'
downloaded 58.0 MB
```

The actual file size on my computer is 60.8Mb. I then ran `remotes::install_github("jmw86069/jamba")` and it worked!

Good learning experience. Thanks @jmw86069 for all of the help. This issue can be closed if you want :)

**Comment by jmw86069** [comment]
This is a new one for me too, glad I could see the resolution!

I appears the problem was the download took longer than the default timeout setting? Changing the timeout to 100 (seconds I assume) fixed the issue. That's odd, I wonder what step in the chain caused the download to take that long? `tracert` may show a slow hop in the chain, I don't know.
